//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VX.Web.ProfileServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileServiceReference.IProfileService")]
    public interface IProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/GetVocabBanks", ReplyAction="http://tempuri.org/IProfileService/GetVocabBanksResponse")]
        int[] GetVocabBanks(System.Guid token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/GetCurrentUserVocabBanks", ReplyAction="http://tempuri.org/IProfileService/GetCurrentUserVocabBanksResponse")]
        int[] GetCurrentUserVocabBanks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/PostVocabBanks", ReplyAction="http://tempuri.org/IProfileService/PostVocabBanksResponse")]
        bool PostVocabBanks(string vocabBanks);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServiceChannel : VX.Web.ProfileServiceReference.IProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceClient : System.ServiceModel.ClientBase<VX.Web.ProfileServiceReference.IProfileService>, VX.Web.ProfileServiceReference.IProfileService {
        
        public ProfileServiceClient() {
        }
        
        public ProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetVocabBanks(System.Guid token) {
            return base.Channel.GetVocabBanks(token);
        }
        
        public int[] GetCurrentUserVocabBanks() {
            return base.Channel.GetCurrentUserVocabBanks();
        }
        
        public bool PostVocabBanks(string vocabBanks) {
            return base.Channel.PostVocabBanks(vocabBanks);
        }
    }
}
